Category draft
heig-AMT/gamify pull request #19
Opened 2020-11-27 14:32 UTC by GTZL1

2020-11-30 16:26 UTC, glsubri requested changes
I also think that you forgot to update both yaml specifications.

Other than thoses points, I think that you did a good job. Hope we can merge soon

2020-11-30 16:26 UTC, glsubri commented on gamify-specs/src/main/resources/api-spec.yaml
> +                $ref: '#/components/schemas/Category'
This endopoint should return all categories. To return only one category, we should have an endpoint of the form `/categories/myCategoryId`

2020-11-30 16:26 UTC, glsubri commented on gamify-specs/src/main/resources/api-spec.yaml
> +          description: success
Do we want to have this kind of architecture or the `/categories/id` type ? I'm in favour of the second version, but we should discuss it with everybody

2020-11-30 16:26 UTC, glsubri commented on gamify-specs/src/test/java/ch/heigvd/gamify/api/spec/defs/CategoriesDef.java
> +public class CategoriesDef implements En
Formatting...

2020-11-30 16:26 UTC, glsubri commented on gamify-specs/src/test/java/ch/heigvd/gamify/api/spec/defs/PayloadDefs.java
> +              +"   "+ environment.getClient().getPayload(container));
Not sure this should stay in "production" code ?

2020-11-30 16:26 UTC, glsubri commented on gamify-specs/src/test/resources/scenarios/categories.feature
> +# Created by David Dupraz at 26.11.2020
Why ?

2020-12-01 08:15 UTC, alexandrepiveteau requested changes
This is a nice start !

There are a few things to answer before merging this PR:

- Do we really want this URL scheme (see the comments by @glsubri)?
- The current model does not allow multiple apps to create a category with the same id (unlike what our spec indicated).
- Formatting is not respected. Please use [this styleguide](https://github.com/heig-AMT/gamify/blob/dev/intellij-java-google-style.xml), it's in the repo 😄

2020-12-01 08:15 UTC, alexandrepiveteau commented on gamify-specs/src/test/resources/scenarios/categories.feature
> +    And I UPDATE category1 to category2 to the /categories endpoint
Since we're using HTTP verbs for Cucumber specs, I suggest we write `PUT` here.

2020-12-01 08:15 UTC, alexandrepiveteau commented on gamify-specs/src/test/java/ch/heigvd/gamify/api/spec/defs/CategoriesDef.java
> +        When("I UPDATE {word} to {word} to the /categories endpoint", (String categoryToUpdate, String newCategory) ->
We should use HTTP verbs here, so `PUT` might be better than `UPDATE`.

2020-12-01 08:15 UTC, alexandrepiveteau commented on gamify-specs/src/test/java/ch/heigvd/gamify/api/spec/defs/CategoriesDef.java
> +            );
What happens on API failures ?

2020-12-01 08:15 UTC, alexandrepiveteau commented on gamify-impl/src/main/resources/api-spec.yaml
> +          nullable: false
This is not the same ending as the other `api-spec.yaml` file, so the CI will not succeed.

2020-12-03 13:23 UTC, alexandrepiveteau commented on gamify-impl/src/main/java/ch/heigvd/gamify/entities/CategoryEntity.java
> +{
```suggestion
public class CategoryEntity implements Serializable {
```

2020-12-03 16:27 UTC, alexandrepiveteau commented
This has been implemented in #22.

2020-12-03 16:27 UTC, closed without merging